# Generated by Django 5.0.1 on 2024-01-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Sell", "Sell")], max_length=5, null=True
            ),
        ),
    ]
