# Generated by Django 5.0.1 on 2024-01-21 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_transactions_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
