# Generated by Django 5.0.1 on 2024-01-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_transactions_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.users"
            ),
        ),
    ]
